import "./globals.css";
import localFont from "next/font/local";

import Sidebar from "@/components/Sidebar";
import HeaderBar from "@/components/HeaderBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = localFont({
  src: [
    { path: "../../public/fonts/Poppins/Poppins-Thin.ttf", weight: "100" },
    {
      path: "../../public/fonts/Poppins/Poppins-ExtraLight.ttf",
      weight: "200",
    },
    { path: "../../public/fonts/Poppins/Poppins-Light.ttf", weight: "300" },
    { path: "../../public/fonts/Poppins/Poppins-Regular.ttf", weight: "400" },
    { path: "../../public/fonts/Poppins/Poppins-Medium.ttf", weight: "500" },
    { path: "../../public/fonts/Poppins/Poppins-SemiBold.ttf", weight: "600" },
    { path: "../../public/fonts/Poppins/Poppins-Bold.ttf", weight: "700" },
    { path: "../../public/fonts/Poppins/Poppins-ExtraBold.ttf", weight: "800" },
    { path: "../../public/fonts/Poppins/Poppins-Black.ttf", weight: "900" },
  ],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <main className="bg-gray-300">
          <div className="flex w-full gap-1 h-screen m-auto">
            <div className="hidden sm:block max-h-[1080px]">
              <Sidebar />
            </div>
            <div className="flex flex-col w-full">
              <HeaderBar />
              <div className="w-full h-screen overflow-y-auto rounded-lg">
                {children}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
